### ISSUE TITLE
Upon death and respawn

### ISSUE THREAD

**Issue by muddup** [dotalw/EssCore#2]
[02:25:38 ERROR]: Could not pass event PlayerRespawnEvent to EssCore v0.7.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:308) ~[spigot.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:500) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:485) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:
654) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.PlayerList.moveToWorld(PlayerList.java:
583) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at com.Zrips.CMI.Reflections.respawn(Reflections.java:936) [CMI8.2.0.2.j
ar:?]
        at com.Zrips.CMI.Containers.CMIUser.respawn(CMIUser.java:1615) [CMI8.2.0
.2.jar:?]
        at com.Zrips.CMI.AllListeners.UserEvents$4.run(UserEvents.java:183) [CMI
8.2.0.2.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.jav
a:81) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHe
artbeat(CraftScheduler.java:391) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:
893) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:
417) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:
835) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.jav
a:733) [spigot.jar:git-Spigot-a1f2566-97b0057]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.IllegalArgumentException: Respawn location can not be null
        at org.apache.commons.lang.Validate.notNull(Validate.java:192) ~[spigot.
jar:git-Spigot-a1f2566-97b0057]
        at org.bukkit.event.player.PlayerRespawnEvent.setRespawnLocation(PlayerR
espawnEvent.java:37) ~[spigot.jar:git-Spigot-a1f2566-97b0057]
        at me.Alw7SHxD.EssCore.listeners.PlayerRespawnHandler.onPlayerRespawn(Pl
ayerRespawnHandler.java:24) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0
_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0
_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_191]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:304) ~[spigot.jar:git-Spigot-a1f2566-97b0057]
        ... 19 more

I did respawn though, so not sure if this is anything really...
THanks,
Muddup

**Comment by dotalw** [comment]
please follow the `Bug Report` issue template, as you're clearly not doing so, then I could easily assist you with this issue.
